# Generated by Django 2.2.1 on 2019-07-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Image',
            field=models.ImageField(upload_to='../media/'),
        ),
    ]
