# Generated by Django 2.1.1 on 2019-07-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190707_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
