# Generated by Django 3.0.2 on 2020-01-26 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='Category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='subscribe',
            table=None,
        ),
    ]
