# Generated by Django 3.0.2 on 2020-01-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200126_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
