# Generated by Django 3.0.2 on 2020-01-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_images_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
